baseURL: https://miniluz.github.io
languageCode: en-us
title: miniluz
theme: PaperMod

params:
  homeInfoParams:
    Title: Welcome!
    Content: "Check out what I've been doing lately:"

  ShowReadingTime: true
